config/routes.rb
Panopticon::Engine.routes.draw do
  mount Panopticon::Engine, at: "/panopticon"
  get 'analysis', to: 'memory_watcher#analysis'
  root to: "memory_watcher#index"
end

app/models/panopticon/application_record.rb
module Panopticon
  class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
  end
end

app/controllers/panopticon/application_controller.rb
module Panopticon
  class ApplicationController < ::ApplicationController
    protect_from_forgery with: :exception
  end
end

app/controllers/panopticon/memory_watcher_controller.rb
module Panopticon
  class MemoryWatcherController < ApplicationController
    def index
      @info = {}
      if File.exist?('../../memtemp.txt')
        File.readlines('../../memtemp.txt').map do |line|
          if line.present?
            controller, action, mem_usage = line.chomp.split('$')
            hash_key = "#{controller}##{action}"
            @info[hash_key] ||= {}
            @info[hash_key] ||= {}
            @info[hash_key][:mem_usage] ||= 0
            @info[hash_key][:count] ||= 0
            @info[hash_key][:max] ||= 0
            mem_usage = mem_usage.to_f

            @info[hash_key][:mem_usage] += mem_usage
            @info[hash_key][:count] += 1
            @info[hash_key][:max] = [@info[hash_key][:max], mem_usage].max
          end
        end
      end
    end

    def analysis
      @info = []
      if File.exist?('../../memtemp.txt')
        File.readlines('../../memtemp.txt').map do |line|
          if line.include?(params[:inquiry])
            _, _, mem_usage = line.chomp.split('$')
            @info << mem_usage
          end
        end
      end
    end
  end
end

app/helpers/panopticon/application_helper.rb
module Panopticon
  module ApplicationHelper
  end
end

app/views/layouts/panopticon/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Panopticon</title>
  <%= csrf_meta_tags %>

</head>
<body>

<%= yield %>

</body>
</html>

app/views/panopticon/memory_watcher/analysis.html.erb
<%= link_to('Back', root_path)%>
<h3>Historical Logs</h3>
<table>
  <tr>
    <th style="border: 1px solid black;padding: 10px;" >Memory Consumption (KBs)</th>
  </tr>
  <% @info.each do |mem_consumption| %>
    <tr>
      <td style="border: 1px solid black;padding: 10px;"> <%= mem_consumption %> </td>
    </tr>
  <% end %>
</table>

app/views/panopticon/memory_watcher/index.html.erb
<table>
  <tr >
    <th style="border: 1px solid black;padding: 10px;">Controller & Action</th>
    <th style="border: 1px solid black;padding: 10px;">Memory Usage Average (KBs)</th>
    <th style="border: 1px solid black;padding: 10px;">Memory Usage Maximum (KBs)</th>
  </tr>
  <% @info.each do |hash_key, a_details| %>
    <tr>
      <td style="border: 1px solid black;padding: 10px;"> <%= link_to(hash_key, analysis_path(inquiry: hash_key.gsub('#','$'))) %> </td>
      <td style="border: 1px solid black;padding: 10px;"> <%= (a_details[:mem_usage] / a_details[:count]).to_i %> </td>
      <td style="border: 1px solid black;padding: 10px;"> <%= a_details[:max].to_i %> </td>
    </tr>
  <% end %>
</table>